draw_boost: 1.4
form_last_n: 6
goals_colsample_bytree: 1.0
goals_gamma: 0.9
goals_learning_rate: 0.02
goals_max_depth: 9
goals_min_child_weight: 2.5
goals_n_estimators: 250
goals_reg_alpha: 0.25
goals_reg_lambda: 1.35
goals_subsample: 0.75
hybrid_poisson_weight: 0.8
min_lambda: 0.29000000000000004
momentum_decay: 0.97
outcome_colsample_bytree: 0.9
outcome_gamma: 1.0
outcome_learning_rate: 0.12
outcome_max_depth: 3
outcome_min_child_weight: 5.5
outcome_n_estimators: 200
outcome_reg_alpha: 0.25
outcome_reg_lambda: 1.15
outcome_subsample: 0.9
poisson_draw_rho: 0.07
prior_blend_alpha: 0.06
prob_source: hybrid
proba_grid_max_goals: 12
proba_temperature: 1.05
time_decay_half_life_days: 330.0
